id: I84970486
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T01:58:06+00:00'
last_modified: '2022-06-08T08:40:55.124461+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25788
  title: འབྲིང་རྒྱུགས་ཉིང་བཅུད་ཀུན་འདུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '2442':
      image_group_id: I1KG25790
      title: ''
      total_pages: 268
      order: 1
      base_file: 2442.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
